# Generated by Django 2.2.4 on 2025-10-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='desc',
            field=models.TextField(default='no descreption provided', verbose_name=1000),
            preserve_default=False,
        ),
    ]
