# Generated by Django 2.2.4 on 2025-10-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ninja_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='desc',
        ),
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='old dojo', verbose_name=1000),
            preserve_default=False,
        ),
    ]
