# Generated by Django 2.2.4 on 2025-10-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('network', models.CharField(max_length=30)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
