# Generated by Django 2.2.4 on 2025-10-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='No Descriptions Yet', max_length=1000),
            preserve_default=False,
        ),
    ]
