# Generated by Django 2.2.4 on 2025-10-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_show_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
