# Generated by Django 2.2.4 on 2025-10-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='No Notes Yet', max_length=30),
            preserve_default=False,
        ),
    ]
