# Generated by Django 2.2.4 on 2025-10-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        ('wallapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.User'),
            preserve_default=False,
        ),
    ]
